### ISSUE TITLE
Consider dialling back on the requirements when initializing NMeta

### ISSUE THREAD

**Issue by pbodsk** [nodes-vapor/n-meta#27]
When attempting to create a new `NMeta` struct as an extension on a `Request` this sanity check exists

    guard components.count == 5 else {
        throw NMetaError.invalidHeaderFormat
    }

This works fine for the native platforms but for a request from a web platform the last three parts can be extracted from the `User-Agent` as described in the README

> For web platform only platform and environment is required, since the rest can be found in User-Agent.

Therefore, we need to extend the checking to consider web and then extract what can be extracted from the `User-Agent` if the platform is `web` before we throws errors

**Comment by siemensikkema** [comment]
closing as it was fixed in #28
